# Generated by Django 3.2.9 on 2021-12-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(max_length=30, verbose_name='Список категорій')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_doc', models.CharField(max_length=30, verbose_name='Номер документа')),
                ('name_doc', models.CharField(max_length=30, verbose_name='Назва документа')),
                ('date_doc', models.DateField(verbose_name='Дата документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['date_doc'],
            },
        ),
        migrations.CreateModel(
            name='Name_technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Назва техніки')),
            ],
            options={
                'verbose_name': 'Назва техніки',
                'verbose_name_plural': 'Назва техніки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='New_technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Серійний номер')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('name_technicians', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.name_technicians', verbose_name='Назва техніки')),
            ],
            options={
                'verbose_name': 'Техніка',
                'verbose_name_plural': 'Техніка',
                'ordering': ['type_techn'],
            },
        ),
        migrations.CreateModel(
            name='Subdivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivisions', models.CharField(max_length=30, verbose_name='Список підрозділів')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділ',
                'ordering': ['subdivisions'],
            },
        ),
        migrations.CreateModel(
            name='Type_technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Тип техніки')),
            ],
            options={
                'verbose_name': 'Тип техніки',
                'verbose_name_plural': 'Тип техніки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Одиниці виміру')),
            ],
            options={
                'verbose_name': 'Одиниці виміру',
                'verbose_name_plural': 'Одиниці виміру',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhereIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість')),
                ('expense', models.FloatField(verbose_name='Видаток')),
                ('remainder', models.FloatField(verbose_name='Залишок')),
                ('receipts', models.FloatField(verbose_name='Надходження')),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.document', verbose_name='Документ')),
                ('id_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.new_technique', verbose_name='Техніка')),
                ('subdivision_which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subdivisions', verbose_name='Підрозділ')),
                ('сategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorys', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Місце знаходження',
                'verbose_name_plural': 'Місце знаходження',
                'ordering': ['id_technique'],
            },
        ),
        migrations.AddField(
            model_name='new_technique',
            name='type_techn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.type_technicians', verbose_name='Тип техніки'),
        ),
        migrations.AddField(
            model_name='new_technique',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.unit', verbose_name='Одиниці виміру'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.whereis', verbose_name='З якого підрозділу')),
                ('subdivision_which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subdivisions', verbose_name='В який')),
            ],
            options={
                'verbose_name': 'Пересування',
                'verbose_name_plural': 'Пересування',
                'ordering': ['from_which'],
            },
        ),
    ]
