# Generated by Django 3.2.9 on 2021-12-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211213_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name_technicians',
            new_name='NameTechnicians',
        ),
    ]
